// Code generated by ent, DO NOT EDIT.

package protectedsetting

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldLTE(FieldID, id))
}

// Key applies equality check predicate on the "key" field. It's identical to KeyEQ.
func Key(v string) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldEQ(FieldKey, v))
}

// Envelope applies equality check predicate on the "envelope" field. It's identical to EnvelopeEQ.
func Envelope(v string) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldEQ(FieldEnvelope, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldEQ(FieldUpdatedAt, v))
}

// KeyEQ applies the EQ predicate on the "key" field.
func KeyEQ(v string) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldEQ(FieldKey, v))
}

// KeyNEQ applies the NEQ predicate on the "key" field.
func KeyNEQ(v string) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldNEQ(FieldKey, v))
}

// KeyIn applies the In predicate on the "key" field.
func KeyIn(vs ...string) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldIn(FieldKey, vs...))
}

// KeyNotIn applies the NotIn predicate on the "key" field.
func KeyNotIn(vs ...string) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldNotIn(FieldKey, vs...))
}

// KeyGT applies the GT predicate on the "key" field.
func KeyGT(v string) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldGT(FieldKey, v))
}

// KeyGTE applies the GTE predicate on the "key" field.
func KeyGTE(v string) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldGTE(FieldKey, v))
}

// KeyLT applies the LT predicate on the "key" field.
func KeyLT(v string) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldLT(FieldKey, v))
}

// KeyLTE applies the LTE predicate on the "key" field.
func KeyLTE(v string) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldLTE(FieldKey, v))
}

// KeyContains applies the Contains predicate on the "key" field.
func KeyContains(v string) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldContains(FieldKey, v))
}

// KeyHasPrefix applies the HasPrefix predicate on the "key" field.
func KeyHasPrefix(v string) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldHasPrefix(FieldKey, v))
}

// KeyHasSuffix applies the HasSuffix predicate on the "key" field.
func KeyHasSuffix(v string) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldHasSuffix(FieldKey, v))
}

// KeyEqualFold applies the EqualFold predicate on the "key" field.
func KeyEqualFold(v string) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldEqualFold(FieldKey, v))
}

// KeyContainsFold applies the ContainsFold predicate on the "key" field.
func KeyContainsFold(v string) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldContainsFold(FieldKey, v))
}

// EnvelopeEQ applies the EQ predicate on the "envelope" field.
func EnvelopeEQ(v string) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldEQ(FieldEnvelope, v))
}

// EnvelopeNEQ applies the NEQ predicate on the "envelope" field.
func EnvelopeNEQ(v string) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldNEQ(FieldEnvelope, v))
}

// EnvelopeIn applies the In predicate on the "envelope" field.
func EnvelopeIn(vs ...string) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldIn(FieldEnvelope, vs...))
}

// EnvelopeNotIn applies the NotIn predicate on the "envelope" field.
func EnvelopeNotIn(vs ...string) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldNotIn(FieldEnvelope, vs...))
}

// EnvelopeGT applies the GT predicate on the "envelope" field.
func EnvelopeGT(v string) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldGT(FieldEnvelope, v))
}

// EnvelopeGTE applies the GTE predicate on the "envelope" field.
func EnvelopeGTE(v string) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldGTE(FieldEnvelope, v))
}

// EnvelopeLT applies the LT predicate on the "envelope" field.
func EnvelopeLT(v string) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldLT(FieldEnvelope, v))
}

// EnvelopeLTE applies the LTE predicate on the "envelope" field.
func EnvelopeLTE(v string) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldLTE(FieldEnvelope, v))
}

// EnvelopeContains applies the Contains predicate on the "envelope" field.
func EnvelopeContains(v string) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldContains(FieldEnvelope, v))
}

// EnvelopeHasPrefix applies the HasPrefix predicate on the "envelope" field.
func EnvelopeHasPrefix(v string) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldHasPrefix(FieldEnvelope, v))
}

// EnvelopeHasSuffix applies the HasSuffix predicate on the "envelope" field.
func EnvelopeHasSuffix(v string) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldHasSuffix(FieldEnvelope, v))
}

// EnvelopeEqualFold applies the EqualFold predicate on the "envelope" field.
func EnvelopeEqualFold(v string) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldEqualFold(FieldEnvelope, v))
}

// EnvelopeContainsFold applies the ContainsFold predicate on the "envelope" field.
func EnvelopeContainsFold(v string) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldContainsFold(FieldEnvelope, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProtectedSetting) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProtectedSetting) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProtectedSetting) predicate.ProtectedSetting {
	return predicate.ProtectedSetting(sql.NotPredicates(p))
}
