// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Wei-Shaw/sub2api/internal/config"
	"github.com/Wei-Shaw/sub2api/internal/handler"
	"github.com/Wei-Shaw/sub2api/internal/handler/admin"
	"github.com/Wei-Shaw/sub2api/internal/repository"
	"github.com/Wei-Shaw/sub2api/internal/securityaudit"
	"github.com/Wei-Shaw/sub2api/internal/server"
	"github.com/Wei-Shaw/sub2api/internal/server/middleware"
	"github.com/Wei-Shaw/sub2api/internal/service"
)

import (
	_ "embed"
	_ "github.com/Wei-Shaw/sub2api/ent/runtime"
)

// Injectors from wire.go:

func initializeApplication(buildInfo handler.BuildInfo) (*Application, error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, err
	}
	client, err := repository.ProvideEnt(configConfig)
	if err != nil {
		return nil, err
	}
	db, err := repository.ProvideSQLDB(client)
	if err != nil {
		return nil, err
	}
	apiKeyRepository, err := repository.NewAPIKeyRepository(client, db)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(client, db)
	groupRepository := repository.NewGroupRepository(client, db)
	userGroupRateRepository := repository.NewUserGroupRateRepository(db)
	redisClient := repository.ProvideRedis(configConfig)
	apiKeyCache := repository.NewAPIKeyCache(redisClient)
	billingCache := repository.NewBillingCache(redisClient)
	userRPMCache := repository.NewUserRPMCache(redisClient)
	billingCacheService := service.ProvidePrivateBillingCacheService(billingCache, apiKeyRepository, userRPMCache, userGroupRateRepository, configConfig)
	concurrencyCache := repository.ProvideConcurrencyCache(redisClient, configConfig)
	schedulerCache := repository.ProvideSchedulerCache(redisClient, configConfig)
	accountRepository, err := repository.NewAccountRepository(client, db, schedulerCache)
	if err != nil {
		return nil, err
	}
	concurrencyService := service.ProvideConcurrencyService(concurrencyCache, accountRepository, configConfig)
	apiKeyService := service.ProvidePrivateAPIKeyService(apiKeyRepository, userRepository, groupRepository, userGroupRateRepository, apiKeyCache, configConfig, billingCacheService, concurrencyService)
	apiKeyHandler := handler.NewAPIKeyHandler(apiKeyService)
	usageLogRepository := repository.NewUsageLogRepository(client, db)
	apiKeyAuthCacheInvalidator := service.ProvideAPIKeyAuthCacheInvalidator(apiKeyService)
	usageService := service.NewUsageService(usageLogRepository, userRepository, client, apiKeyAuthCacheInvalidator)
	opsRepository, err := repository.NewOpsRepository(db)
	if err != nil {
		return nil, err
	}
	settingRepository := repository.NewSettingRepository(client)
	usageBillingRepository := repository.NewUsageBillingRepository(client, db)
	gatewayCache := repository.NewGatewayCache(redisClient)
	schedulerOutboxRepository := repository.NewSchedulerOutboxRepository(db)
	schedulerSnapshotService := service.ProvideSchedulerSnapshotService(schedulerCache, schedulerOutboxRepository, accountRepository, groupRepository, configConfig)
	pricingRemoteClient := repository.ProvidePricingRemoteClient(configConfig)
	pricingService, err := service.ProvidePricingService(configConfig, pricingRemoteClient)
	if err != nil {
		return nil, err
	}
	billingService := service.NewBillingService(configConfig, pricingService)
	geminiQuotaService := service.NewGeminiQuotaService(configConfig, settingRepository)
	tempUnschedCache := repository.NewTempUnschedCache(redisClient)
	timeoutCounterCache := repository.NewTimeoutCounterCache(redisClient)
	openAI403CounterCache := repository.NewOpenAI403CounterCache(redisClient)
	proxyRepository := repository.NewProxyRepository(client, db)
	settingService := service.ProvideSettingService(settingRepository, groupRepository, proxyRepository, configConfig)
	geminiTokenCache := repository.NewGeminiTokenCache(redisClient)
	compositeTokenCacheInvalidator := service.NewCompositeTokenCacheInvalidator(geminiTokenCache)
	rateLimitService := service.ProvideRateLimitService(accountRepository, usageLogRepository, configConfig, geminiQuotaService, tempUnschedCache, timeoutCounterCache, openAI403CounterCache, settingService, compositeTokenCacheInvalidator)
	identityCache := repository.NewIdentityCache(redisClient)
	identityService := service.NewIdentityService(identityCache)
	httpUpstream := repository.NewHTTPUpstream(configConfig)
	timingWheelService, err := service.ProvideTimingWheelService()
	if err != nil {
		return nil, err
	}
	deferredService := service.ProvideDeferredService(accountRepository, timingWheelService)
	claudeOAuthClient := repository.NewClaudeOAuthClient()
	oAuthService := service.NewOAuthService(proxyRepository, claudeOAuthClient)
	oAuthRefreshAPI := service.ProvideOAuthRefreshAPI(accountRepository, geminiTokenCache)
	claudeTokenProvider := service.ProvideClaudeTokenProvider(accountRepository, geminiTokenCache, oAuthService, oAuthRefreshAPI)
	sessionLimitCache := repository.ProvideSessionLimitCache(redisClient, configConfig)
	rpmCache := repository.NewRPMCache(redisClient)
	digestSessionStore := service.NewDigestSessionStore()
	tlsFingerprintProfileRepository := repository.NewTLSFingerprintProfileRepository(client)
	tlsFingerprintProfileCache := repository.NewTLSFingerprintProfileCache(redisClient)
	tlsFingerprintProfileService := service.NewTLSFingerprintProfileService(tlsFingerprintProfileRepository, tlsFingerprintProfileCache)
	channelRepository := repository.NewChannelRepository(db)
	channelService := service.NewChannelService(channelRepository, groupRepository, apiKeyAuthCacheInvalidator, pricingService)
	modelPricingResolver := service.NewModelPricingResolver(channelService, billingService)
	compositeModelRouteRepository := repository.NewCompositeModelRouteRepository(client)
	compositeRouteResolver := service.NewCompositeRouteResolver(compositeModelRouteRepository)
	gatewayService := service.NewPrivateGatewayService(accountRepository, groupRepository, usageLogRepository, usageBillingRepository, userRepository, userGroupRateRepository, gatewayCache, configConfig, schedulerSnapshotService, concurrencyService, billingService, rateLimitService, billingCacheService, identityService, httpUpstream, deferredService, claudeTokenProvider, sessionLimitCache, rpmCache, digestSessionStore, settingService, tlsFingerprintProfileService, channelService, modelPricingResolver, compositeRouteResolver)
	openAIOAuthClient := repository.NewOpenAIOAuthClient()
	privacyClientFactory := providePrivacyClientFactory()
	openAIOAuthService := service.ProvideOpenAIOAuthService(proxyRepository, openAIOAuthClient, privacyClientFactory)
	openAITokenProvider := service.ProvideOpenAITokenProvider(accountRepository, geminiTokenCache, openAIOAuthService, oAuthRefreshAPI)
	grokOAuthClient := repository.NewGrokOAuthClient()
	grokOAuthService := service.NewGrokOAuthService(proxyRepository, grokOAuthClient)
	grokTokenProvider := service.ProvideGrokTokenProvider(accountRepository, geminiTokenCache, grokOAuthService, oAuthRefreshAPI, tempUnschedCache)
	openAIGatewayService := service.NewPrivateOpenAIGatewayService(accountRepository, usageLogRepository, usageBillingRepository, userRepository, userGroupRateRepository, gatewayCache, configConfig, schedulerSnapshotService, concurrencyService, billingService, rateLimitService, billingCacheService, httpUpstream, deferredService, openAITokenProvider, grokTokenProvider, modelPricingResolver, channelService, settingService)
	geminiOAuthClient := repository.NewGeminiOAuthClient(configConfig)
	geminiCliCodeAssistClient := repository.NewGeminiCliCodeAssistClient()
	driveClient := repository.NewGeminiDriveClient()
	geminiOAuthService := service.NewGeminiOAuthService(proxyRepository, geminiOAuthClient, geminiCliCodeAssistClient, driveClient, configConfig)
	geminiTokenProvider := service.ProvideGeminiTokenProvider(accountRepository, geminiTokenCache, geminiOAuthService, oAuthRefreshAPI)
	antigravityOAuthService := service.NewAntigravityOAuthService(proxyRepository)
	antigravityTokenProvider := service.ProvideAntigravityTokenProvider(accountRepository, geminiTokenCache, antigravityOAuthService, oAuthRefreshAPI, tempUnschedCache)
	internal500CounterCache := repository.NewInternal500CounterCache(redisClient)
	antigravityGatewayService := service.NewAntigravityGatewayService(accountRepository, gatewayCache, schedulerSnapshotService, antigravityTokenProvider, rateLimitService, httpUpstream, settingService, internal500CounterCache)
	geminiMessagesCompatService := service.NewGeminiMessagesCompatService(accountRepository, groupRepository, gatewayCache, schedulerSnapshotService, geminiTokenProvider, rateLimitService, httpUpstream, antigravityGatewayService, configConfig)
	opsSystemLogSink := service.ProvideOpsSystemLogSink(opsRepository)
	authCacheInvalidationOutboxRepository := repository.NewAuthCacheInvalidationOutboxRepository(db)
	authCacheInvalidationWorker := service.ProvideAuthCacheInvalidationWorker(authCacheInvalidationOutboxRepository, apiKeyCache, apiKeyService)
	opsService := service.ProvideOpsService(opsRepository, settingRepository, configConfig, accountRepository, userRepository, concurrencyService, gatewayService, openAIGatewayService, geminiMessagesCompatService, antigravityGatewayService, opsSystemLogSink, settingService, authCacheInvalidationWorker, apiKeyService)
	usageHandler := handler.NewUsageHandler(usageService, apiKeyService, opsService, settingService)
	channelMonitorRepository := repository.NewChannelMonitorRepository(client, db)
	secretEncryptor, err := repository.NewAESEncryptor(configConfig)
	if err != nil {
		return nil, err
	}
	channelMonitorService := service.ProvideChannelMonitorService(channelMonitorRepository, secretEncryptor)
	channelMonitorUserHandler := handler.NewChannelMonitorUserHandler(channelMonitorService, settingService)
	dashboardAggregationRepository := repository.NewDashboardAggregationRepository(db)
	dashboardStatsCache := repository.NewDashboardCache(redisClient, configConfig)
	dashboardService := service.NewDashboardService(usageLogRepository, dashboardAggregationRepository, dashboardStatsCache, configConfig)
	leaderLockCache := repository.NewLeaderLockCache(redisClient)
	dashboardAggregationService := service.ProvideDashboardAggregationService(dashboardAggregationRepository, timingWheelService, leaderLockCache, db, configConfig)
	dashboardHandler := admin.NewDashboardHandler(dashboardService, dashboardAggregationService)
	adminGroupRepository := repository.NewAdminGroupRepository(client, db)
	adminAccountRepository, err := repository.NewAdminAccountRepository(client, db, schedulerCache)
	if err != nil {
		return nil, err
	}
	redeemCodeRepository := repository.NewRedeemCodeRepository(client)
	proxyExitInfoProber := repository.NewProxyExitInfoProber(configConfig)
	proxyLatencyCache := repository.NewProxyLatencyCache(redisClient)
	adminService := service.NewPrivateAdminService(userRepository, adminGroupRepository, adminAccountRepository, proxyRepository, apiKeyRepository, redeemCodeRepository, userGroupRateRepository, userRPMCache, billingCacheService, proxyExitInfoProber, proxyLatencyCache, apiKeyAuthCacheInvalidator, client, settingService, privacyClientFactory, openAIGatewayService, compositeModelRouteRepository, compositeRouteResolver)
	groupCapacityService := service.NewGroupCapacityService(accountRepository, groupRepository, concurrencyService, sessionLimitCache, rpmCache)
	groupHandler := admin.NewGroupHandler(adminService, dashboardService, groupCapacityService)
	claudeUsageFetcher := repository.NewClaudeUsageFetcher(httpUpstream)
	antigravityQuotaFetcher := service.NewAntigravityQuotaFetcher(proxyRepository)
	grokQuotaFetcher := service.NewGrokQuotaFetcher()
	grokQuotaService := service.ProvideGrokQuotaService(accountRepository, proxyRepository, grokTokenProvider, httpUpstream, configConfig, usageLogRepository)
	openAIQuotaService := service.ProvideOpenAIQuotaService(accountRepository, proxyRepository, openAITokenProvider, privacyClientFactory, openAIGatewayService)
	usageCache := service.NewUsageCache()
	accountUsageService := service.ProvideAccountUsageService(accountRepository, usageLogRepository, claudeUsageFetcher, geminiQuotaService, antigravityQuotaFetcher, grokQuotaFetcher, grokQuotaService, openAIQuotaService, usageCache, identityCache, tlsFingerprintProfileService, openAIGatewayService)
	accountTestService := service.ProvideAccountTestService(accountRepository, geminiTokenProvider, claudeTokenProvider, grokTokenProvider, antigravityGatewayService, httpUpstream, configConfig, tlsFingerprintProfileService, openAIGatewayService, accountUsageService)
	crsSyncService := service.NewCRSSyncService(accountRepository, proxyRepository, oAuthService, openAIOAuthService, geminiOAuthService, configConfig)
	accountHandler := admin.ProvideAccountHandler(adminService, oAuthService, openAIOAuthService, geminiOAuthService, antigravityOAuthService, grokOAuthService, rateLimitService, accountUsageService, accountTestService, concurrencyService, crsSyncService, sessionLimitCache, rpmCache, compositeTokenCacheInvalidator, grokQuotaService)
	dataManagementService := service.NewDataManagementService()
	dataManagementHandler := admin.NewDataManagementHandler(dataManagementService)
	backupObjectStoreFactory := repository.NewS3BackupStoreFactory()
	dbDumper := repository.NewPgDumper(configConfig)
	backupService, err := service.ProvideBackupService(settingRepository, configConfig, secretEncryptor, backupObjectStoreFactory, dbDumper)
	if err != nil {
		return nil, err
	}
	userService := service.NewUserService(userRepository, settingRepository, apiKeyAuthCacheInvalidator, billingCache)
	imageStorageFactory := repository.ProvideImageStorageFactory()
	imageStorageSettingService := service.ProvideImageStorageSettingService(settingRepository, secretEncryptor, backupService, imageStorageFactory, configConfig)
	backupHandler := admin.NewBackupHandler(backupService, userService, imageStorageSettingService)
	oAuthHandler := admin.NewOAuthHandler(oAuthService)
	openAIOAuthHandler := admin.NewOpenAIOAuthHandler(openAIOAuthService, adminService, openAIQuotaService, rateLimitService)
	geminiOAuthHandler := admin.NewGeminiOAuthHandler(geminiOAuthService)
	antigravityOAuthHandler := admin.NewAntigravityOAuthHandler(antigravityOAuthService)
	tokenRefreshService := service.ProvideTokenRefreshService(accountRepository, oAuthService, openAIOAuthService, geminiOAuthService, antigravityOAuthService, grokOAuthService, compositeTokenCacheInvalidator, schedulerCache, configConfig, tempUnschedCache, privacyClientFactory, proxyRepository, oAuthRefreshAPI, openAIGatewayService)
	grokOAuthHandler := admin.NewGrokOAuthHandler(grokOAuthService, adminService, grokQuotaService, tokenRefreshService)
	proxyHandler := admin.NewProxyHandler(adminService)
	emailCache := repository.NewEmailCache(redisClient)
	emailService := service.NewEmailService(settingRepository, emailCache)
	notificationEmailService := service.NewNotificationEmailService(settingRepository, emailService)
	settingHandler := handler.ProvidePrivateAdminSettingHandler(settingService, emailService, opsService, notificationEmailService)
	opsHandler := admin.NewOpsHandler(opsService)
	updateCache := repository.NewUpdateCache(redisClient)
	gitHubReleaseClient := repository.ProvideGitHubReleaseClient(configConfig)
	serviceBuildInfo := provideServiceBuildInfo(buildInfo)
	updateService := service.ProvideUpdateService(updateCache, gitHubReleaseClient, serviceBuildInfo)
	idempotencyRepository := repository.NewIdempotencyRepository(client, db)
	systemOperationLockService := service.ProvideSystemOperationLockService(idempotencyRepository, configConfig)
	systemHandler := handler.ProvideSystemHandler(updateService, systemOperationLockService)
	usageCleanupRepository := repository.NewUsageCleanupRepository(client, db)
	usageCleanupService := service.ProvideUsageCleanupService(usageCleanupRepository, timingWheelService, dashboardAggregationService, configConfig)
	adminUsageHandler := admin.NewUsageHandler(usageService, apiKeyService, adminService, usageCleanupService)
	errorPassthroughRepository := repository.NewErrorPassthroughRepository(client)
	errorPassthroughCache := repository.NewErrorPassthroughCache(redisClient)
	errorPassthroughService := service.NewErrorPassthroughService(errorPassthroughRepository, errorPassthroughCache)
	errorPassthroughHandler := admin.NewErrorPassthroughHandler(errorPassthroughService)
	tlsFingerprintProfileHandler := admin.NewTLSFingerprintProfileHandler(tlsFingerprintProfileService)
	adminAPIKeyHandler := admin.NewAdminAPIKeyHandler(adminService)
	scheduledTestPlanRepository := repository.NewScheduledTestPlanRepository(db)
	scheduledTestResultRepository := repository.NewScheduledTestResultRepository(db)
	scheduledTestService := service.ProvideScheduledTestService(scheduledTestPlanRepository, scheduledTestResultRepository)
	scheduledTestHandler := admin.NewScheduledTestHandler(scheduledTestService)
	channelHandler := admin.NewChannelHandler(channelService, billingService, pricingService)
	channelMonitorHandler := admin.NewChannelMonitorHandler(channelMonitorService)
	channelMonitorRequestTemplateRepository := repository.NewChannelMonitorRequestTemplateRepository(client, db)
	channelMonitorRequestTemplateService := service.NewChannelMonitorRequestTemplateService(channelMonitorRequestTemplateRepository)
	channelMonitorRequestTemplateHandler := admin.NewChannelMonitorRequestTemplateHandler(channelMonitorRequestTemplateService)
	contentModerationRepository := repository.NewContentModerationRepository(db)
	contentModerationHashCache := repository.NewContentModerationHashCache(redisClient)
	contentModerationService := service.ProvideContentModerationService(settingRepository, contentModerationRepository, contentModerationHashCache, groupRepository, userRepository, proxyRepository, apiKeyAuthCacheInvalidator, emailService)
	contentModerationHandler := admin.NewContentModerationHandler(contentModerationService)
	configManager := securityaudit.NewConfigManager(db, settingRepository, redisClient, secretEncryptor, configConfig)
	postgreSQLRepository := securityaudit.NewPostgreSQLRepository(db)
	redisPayloadStore := securityaudit.NewRedisPayloadStore(redisClient)
	openAICompatibleScanner := securityaudit.NewOpenAICompatibleScanner()
	atomicMetrics := securityaudit.NewAtomicMetrics()
	promptService := securityaudit.NewPromptService(configManager, postgreSQLRepository, redisPayloadStore, openAICompatibleScanner, atomicMetrics)
	promptAdminHandler := securityaudit.NewPromptAdminHandler(promptService)
	auditLogRepository := repository.NewAuditLogRepository(db)
	auditLogService := service.ProvideAuditLogService(auditLogRepository, settingService)
	auditLogHandler := admin.NewAuditLogHandler(auditLogService)
	upstreamBillingProbeService := service.ProvideUpstreamBillingProbeService(accountRepository, accountTestService, settingService, leaderLockCache, db)
	cockpitService := service.NewCockpitService(db)
	ollamaCloudUsageService := service.ProvideOllamaCloudUsageService(accountRepository, httpUpstream, settingService, secretEncryptor, configConfig, leaderLockCache, db)
	adminHandlers := handler.ProvidePrivateAdminHandlers(dashboardHandler, groupHandler, accountHandler, dataManagementHandler, backupHandler, oAuthHandler, openAIOAuthHandler, geminiOAuthHandler, antigravityOAuthHandler, grokOAuthHandler, proxyHandler, settingHandler, opsHandler, systemHandler, adminUsageHandler, errorPassthroughHandler, tlsFingerprintProfileHandler, adminAPIKeyHandler, scheduledTestHandler, channelHandler, channelMonitorHandler, channelMonitorRequestTemplateHandler, contentModerationHandler, promptAdminHandler, auditLogHandler, upstreamBillingProbeService, cockpitService, ollamaCloudUsageService)
	usageRecordWorkerPool := service.NewUsageRecordWorkerPool(configConfig)
	userMsgQueueCache := repository.NewUserMsgQueueCache(redisClient)
	userMessageQueueService := service.ProvideUserMessageQueueService(userMsgQueueCache, rpmCache, configConfig)
	legacyEngine := securityaudit.NewLegacyModerationAdapter(contentModerationService)
	coordinator := securityaudit.NewCoordinator(legacyEngine, promptService)
	gatewayHandler := handler.ProvideGatewayHandler(gatewayService, openAIGatewayService, geminiMessagesCompatService, antigravityGatewayService, userService, concurrencyService, billingCacheService, usageService, apiKeyService, usageRecordWorkerPool, errorPassthroughService, contentModerationService, userMessageQueueService, configConfig, settingService, coordinator)
	openAIGatewayHandler := handler.ProvideOpenAIGatewayHandler(openAIGatewayService, concurrencyService, billingCacheService, apiKeyService, usageRecordWorkerPool, errorPassthroughService, contentModerationService, opsService, grokQuotaService, configConfig, coordinator)
	handlerSettingHandler := handler.ProvideSettingHandler(settingService, buildInfo, notificationEmailService)
	imageTaskStore := repository.NewImageTaskStore(redisClient)
	imageTaskService := service.ProvideImageTaskService(imageTaskStore, imageStorageSettingService)
	asyncImageHandler := handler.NewAsyncImageHandler(imageTaskService, openAIGatewayHandler)
	batchImageRepository := repository.NewBatchImageRepository(db)
	batchImageQueue := repository.NewBatchImageQueue(redisClient, configConfig)
	batchImageModelPricingResolver := service.ProvideBatchImageModelPricingResolver(modelPricingResolver)
	batchImagePublicService := service.NewPrivateBatchImagePublicService(batchImageRepository, accountRepository, groupRepository, userGroupRateRepository, batchImageQueue, batchImageModelPricingResolver, apiKeyAuthCacheInvalidator, configConfig)
	batchImageDownloadLimiter := repository.NewBatchImageDownloadLimiter(redisClient, configConfig)
	batchImageDownloadService := service.NewBatchImageDownloadService(batchImageRepository, accountRepository, batchImageDownloadLimiter, configConfig)
	batchImageCleanupService := service.ProvideBatchImageCleanupService(batchImageRepository, accountRepository, configConfig)
	batchImageHandler := handler.ProvideBatchImageHandler(batchImagePublicService, batchImageDownloadService, batchImageCleanupService, openAIGatewayHandler, apiKeyService, billingCacheService)
	idempotencyCoordinator := service.ProvideIdempotencyCoordinator(idempotencyRepository, configConfig)
	idempotencyCleanupService := service.ProvideIdempotencyCleanupService(idempotencyRepository, configConfig)
	handlers := handler.ProvidePrivateHandlers(apiKeyHandler, usageHandler, channelMonitorUserHandler, adminHandlers, gatewayHandler, openAIGatewayHandler, handlerSettingHandler, asyncImageHandler, batchImageHandler, idempotencyCoordinator, idempotencyCleanupService)
	apiKeyAuthMiddleware := middleware.NewPrivateAPIKeyAuthMiddleware(apiKeyService, configConfig)
	publicRouter := server.ProvidePublicRouter(configConfig, handlers, apiKeyAuthMiddleware, apiKeyService, opsService, settingService, compositeRouteResolver, db, redisClient)
	operatorAuthMiddleware := middleware.NewOperatorAuthMiddleware(userService)
	auditLogMiddleware := middleware.NewAuditLogMiddleware(auditLogService)
	panelRateLimiter := middleware.NewPanelRateLimiter(redisClient, settingService)
	controlRouter := server.ProvideControlRouter(configConfig, handlers, operatorAuthMiddleware, auditLogMiddleware, panelRateLimiter, opsService, settingService, db, redisClient)
	httpServers := server.ProvideHTTPServers(configConfig, publicRouter, controlRouter)
	opsMetricsCollector := service.ProvideOpsMetricsCollector(opsRepository, settingRepository, accountRepository, concurrencyService, db, redisClient, configConfig)
	opsAggregationService := service.ProvideOpsAggregationService(opsRepository, settingRepository, db, redisClient, configConfig)
	opsAlertEvaluatorService := service.ProvideOpsAlertEvaluatorService(opsService, opsRepository, emailService, redisClient, configConfig, proxyRepository)
	opsCleanupService := service.ProvideOpsCleanupService(opsRepository, db, redisClient, configConfig, channelMonitorService, settingRepository, opsService)
	opsScheduledReportService := service.ProvideOpsScheduledReportService(opsService, userService, emailService, redisClient, configConfig)
	opsIngressRejectAggregator := service.ProvideOpsIngressRejectAggregator(opsRepository, opsService)
	accountExpiryService := service.ProvideAccountExpiryService(accountRepository)
	proxyExpiryService := service.ProvideProxyExpiryService(proxyRepository)
	batchImageWorkerRuntime := service.ProvidePrivateBatchImageWorkerRuntime(batchImageRepository, accountRepository, batchImageQueue, usageBillingRepository, billingCacheService, usageLogRepository, batchImageModelPricingResolver, apiKeyAuthCacheInvalidator, configConfig)
	emailQueueService := service.ProvideEmailQueueService(emailService)
	scheduledTestRunnerService := service.ProvideScheduledTestRunnerService(scheduledTestPlanRepository, scheduledTestService, accountTestService, rateLimitService, configConfig)
	channelMonitorRunner := service.ProvideChannelMonitorRunner(channelMonitorService, settingService)
	mainShutdownCoordinator := provideCleanup(client, redisClient, opsMetricsCollector, opsAggregationService, opsAlertEvaluatorService, opsCleanupService, opsScheduledReportService, opsSystemLogSink, opsService, opsIngressRejectAggregator, apiKeyService, authCacheInvalidationWorker, schedulerSnapshotService, tokenRefreshService, accountExpiryService, proxyExpiryService, usageCleanupService, idempotencyCleanupService, batchImageCleanupService, batchImageWorkerRuntime, pricingService, emailQueueService, billingCacheService, usageRecordWorkerPool, oAuthService, openAIOAuthService, geminiOAuthService, antigravityOAuthService, grokOAuthService, openAIGatewayService, scheduledTestRunnerService, backupService, channelMonitorRunner, upstreamBillingProbeService, auditLogService, promptService)
	application := &Application{
		Servers:     httpServers,
		PromptAudit: promptService,
		Cleanup:     mainShutdownCoordinator,
	}
	return application, nil
}

// wire.go:

func providePrivacyClientFactory() service.PrivacyClientFactory {
	return repository.CreatePrivacyReqClient
}

func provideServiceBuildInfo(buildInfo handler.BuildInfo) service.BuildInfo {
	return service.BuildInfo{
		Version:   buildInfo.Version,
		BuildType: buildInfo.BuildType,
	}
}
