// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/protectedsetting"
)

// ProtectedSettingUpdate is the builder for updating ProtectedSetting entities.
type ProtectedSettingUpdate struct {
	config
	hooks    []Hook
	mutation *ProtectedSettingMutation
}

// Where appends a list predicates to the ProtectedSettingUpdate builder.
func (_u *ProtectedSettingUpdate) Where(ps ...predicate.ProtectedSetting) *ProtectedSettingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKey sets the "key" field.
func (_u *ProtectedSettingUpdate) SetKey(v string) *ProtectedSettingUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *ProtectedSettingUpdate) SetNillableKey(v *string) *ProtectedSettingUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetEnvelope sets the "envelope" field.
func (_u *ProtectedSettingUpdate) SetEnvelope(v string) *ProtectedSettingUpdate {
	_u.mutation.SetEnvelope(v)
	return _u
}

// SetNillableEnvelope sets the "envelope" field if the given value is not nil.
func (_u *ProtectedSettingUpdate) SetNillableEnvelope(v *string) *ProtectedSettingUpdate {
	if v != nil {
		_u.SetEnvelope(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProtectedSettingUpdate) SetUpdatedAt(v time.Time) *ProtectedSettingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ProtectedSettingMutation object of the builder.
func (_u *ProtectedSettingUpdate) Mutation() *ProtectedSettingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProtectedSettingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProtectedSettingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProtectedSettingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProtectedSettingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProtectedSettingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := protectedsetting.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProtectedSettingUpdate) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := protectedsetting.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "ProtectedSetting.key": %w`, err)}
		}
	}
	return nil
}

func (_u *ProtectedSettingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(protectedsetting.Table, protectedsetting.Columns, sqlgraph.NewFieldSpec(protectedsetting.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(protectedsetting.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Envelope(); ok {
		_spec.SetField(protectedsetting.FieldEnvelope, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(protectedsetting.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{protectedsetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProtectedSettingUpdateOne is the builder for updating a single ProtectedSetting entity.
type ProtectedSettingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProtectedSettingMutation
}

// SetKey sets the "key" field.
func (_u *ProtectedSettingUpdateOne) SetKey(v string) *ProtectedSettingUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *ProtectedSettingUpdateOne) SetNillableKey(v *string) *ProtectedSettingUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetEnvelope sets the "envelope" field.
func (_u *ProtectedSettingUpdateOne) SetEnvelope(v string) *ProtectedSettingUpdateOne {
	_u.mutation.SetEnvelope(v)
	return _u
}

// SetNillableEnvelope sets the "envelope" field if the given value is not nil.
func (_u *ProtectedSettingUpdateOne) SetNillableEnvelope(v *string) *ProtectedSettingUpdateOne {
	if v != nil {
		_u.SetEnvelope(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProtectedSettingUpdateOne) SetUpdatedAt(v time.Time) *ProtectedSettingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ProtectedSettingMutation object of the builder.
func (_u *ProtectedSettingUpdateOne) Mutation() *ProtectedSettingMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProtectedSettingUpdate builder.
func (_u *ProtectedSettingUpdateOne) Where(ps ...predicate.ProtectedSetting) *ProtectedSettingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProtectedSettingUpdateOne) Select(field string, fields ...string) *ProtectedSettingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProtectedSetting entity.
func (_u *ProtectedSettingUpdateOne) Save(ctx context.Context) (*ProtectedSetting, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProtectedSettingUpdateOne) SaveX(ctx context.Context) *ProtectedSetting {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProtectedSettingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProtectedSettingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProtectedSettingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := protectedsetting.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProtectedSettingUpdateOne) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := protectedsetting.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "ProtectedSetting.key": %w`, err)}
		}
	}
	return nil
}

func (_u *ProtectedSettingUpdateOne) sqlSave(ctx context.Context) (_node *ProtectedSetting, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(protectedsetting.Table, protectedsetting.Columns, sqlgraph.NewFieldSpec(protectedsetting.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProtectedSetting.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, protectedsetting.FieldID)
		for _, f := range fields {
			if !protectedsetting.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != protectedsetting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(protectedsetting.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Envelope(); ok {
		_spec.SetField(protectedsetting.FieldEnvelope, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(protectedsetting.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ProtectedSetting{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{protectedsetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
