// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/protectedsetting"
)

// ProtectedSettingCreate is the builder for creating a ProtectedSetting entity.
type ProtectedSettingCreate struct {
	config
	mutation *ProtectedSettingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetKey sets the "key" field.
func (_c *ProtectedSettingCreate) SetKey(v string) *ProtectedSettingCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetEnvelope sets the "envelope" field.
func (_c *ProtectedSettingCreate) SetEnvelope(v string) *ProtectedSettingCreate {
	_c.mutation.SetEnvelope(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProtectedSettingCreate) SetUpdatedAt(v time.Time) *ProtectedSettingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProtectedSettingCreate) SetNillableUpdatedAt(v *time.Time) *ProtectedSettingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the ProtectedSettingMutation object of the builder.
func (_c *ProtectedSettingCreate) Mutation() *ProtectedSettingMutation {
	return _c.mutation
}

// Save creates the ProtectedSetting in the database.
func (_c *ProtectedSettingCreate) Save(ctx context.Context) (*ProtectedSetting, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProtectedSettingCreate) SaveX(ctx context.Context) *ProtectedSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProtectedSettingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProtectedSettingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProtectedSettingCreate) defaults() {
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := protectedsetting.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProtectedSettingCreate) check() error {
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "ProtectedSetting.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := protectedsetting.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "ProtectedSetting.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Envelope(); !ok {
		return &ValidationError{Name: "envelope", err: errors.New(`ent: missing required field "ProtectedSetting.envelope"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProtectedSetting.updated_at"`)}
	}
	return nil
}

func (_c *ProtectedSettingCreate) sqlSave(ctx context.Context) (*ProtectedSetting, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProtectedSettingCreate) createSpec() (*ProtectedSetting, *sqlgraph.CreateSpec) {
	var (
		_node = &ProtectedSetting{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(protectedsetting.Table, sqlgraph.NewFieldSpec(protectedsetting.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(protectedsetting.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Envelope(); ok {
		_spec.SetField(protectedsetting.FieldEnvelope, field.TypeString, value)
		_node.Envelope = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(protectedsetting.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProtectedSetting.Create().
//		SetKey(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProtectedSettingUpsert) {
//			SetKey(v+v).
//		}).
//		Exec(ctx)
func (_c *ProtectedSettingCreate) OnConflict(opts ...sql.ConflictOption) *ProtectedSettingUpsertOne {
	_c.conflict = opts
	return &ProtectedSettingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProtectedSetting.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProtectedSettingCreate) OnConflictColumns(columns ...string) *ProtectedSettingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProtectedSettingUpsertOne{
		create: _c,
	}
}

type (
	// ProtectedSettingUpsertOne is the builder for "upsert"-ing
	//  one ProtectedSetting node.
	ProtectedSettingUpsertOne struct {
		create *ProtectedSettingCreate
	}

	// ProtectedSettingUpsert is the "OnConflict" setter.
	ProtectedSettingUpsert struct {
		*sql.UpdateSet
	}
)

// SetKey sets the "key" field.
func (u *ProtectedSettingUpsert) SetKey(v string) *ProtectedSettingUpsert {
	u.Set(protectedsetting.FieldKey, v)
	return u
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *ProtectedSettingUpsert) UpdateKey() *ProtectedSettingUpsert {
	u.SetExcluded(protectedsetting.FieldKey)
	return u
}

// SetEnvelope sets the "envelope" field.
func (u *ProtectedSettingUpsert) SetEnvelope(v string) *ProtectedSettingUpsert {
	u.Set(protectedsetting.FieldEnvelope, v)
	return u
}

// UpdateEnvelope sets the "envelope" field to the value that was provided on create.
func (u *ProtectedSettingUpsert) UpdateEnvelope() *ProtectedSettingUpsert {
	u.SetExcluded(protectedsetting.FieldEnvelope)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProtectedSettingUpsert) SetUpdatedAt(v time.Time) *ProtectedSettingUpsert {
	u.Set(protectedsetting.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProtectedSettingUpsert) UpdateUpdatedAt() *ProtectedSettingUpsert {
	u.SetExcluded(protectedsetting.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ProtectedSetting.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProtectedSettingUpsertOne) UpdateNewValues() *ProtectedSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProtectedSetting.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProtectedSettingUpsertOne) Ignore() *ProtectedSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProtectedSettingUpsertOne) DoNothing() *ProtectedSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProtectedSettingCreate.OnConflict
// documentation for more info.
func (u *ProtectedSettingUpsertOne) Update(set func(*ProtectedSettingUpsert)) *ProtectedSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProtectedSettingUpsert{UpdateSet: update})
	}))
	return u
}

// SetKey sets the "key" field.
func (u *ProtectedSettingUpsertOne) SetKey(v string) *ProtectedSettingUpsertOne {
	return u.Update(func(s *ProtectedSettingUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *ProtectedSettingUpsertOne) UpdateKey() *ProtectedSettingUpsertOne {
	return u.Update(func(s *ProtectedSettingUpsert) {
		s.UpdateKey()
	})
}

// SetEnvelope sets the "envelope" field.
func (u *ProtectedSettingUpsertOne) SetEnvelope(v string) *ProtectedSettingUpsertOne {
	return u.Update(func(s *ProtectedSettingUpsert) {
		s.SetEnvelope(v)
	})
}

// UpdateEnvelope sets the "envelope" field to the value that was provided on create.
func (u *ProtectedSettingUpsertOne) UpdateEnvelope() *ProtectedSettingUpsertOne {
	return u.Update(func(s *ProtectedSettingUpsert) {
		s.UpdateEnvelope()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProtectedSettingUpsertOne) SetUpdatedAt(v time.Time) *ProtectedSettingUpsertOne {
	return u.Update(func(s *ProtectedSettingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProtectedSettingUpsertOne) UpdateUpdatedAt() *ProtectedSettingUpsertOne {
	return u.Update(func(s *ProtectedSettingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ProtectedSettingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProtectedSettingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProtectedSettingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ProtectedSettingUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ProtectedSettingUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ProtectedSettingCreateBulk is the builder for creating many ProtectedSetting entities in bulk.
type ProtectedSettingCreateBulk struct {
	config
	err      error
	builders []*ProtectedSettingCreate
	conflict []sql.ConflictOption
}

// Save creates the ProtectedSetting entities in the database.
func (_c *ProtectedSettingCreateBulk) Save(ctx context.Context) ([]*ProtectedSetting, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProtectedSetting, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProtectedSettingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProtectedSettingCreateBulk) SaveX(ctx context.Context) []*ProtectedSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProtectedSettingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProtectedSettingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProtectedSetting.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProtectedSettingUpsert) {
//			SetKey(v+v).
//		}).
//		Exec(ctx)
func (_c *ProtectedSettingCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProtectedSettingUpsertBulk {
	_c.conflict = opts
	return &ProtectedSettingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProtectedSetting.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProtectedSettingCreateBulk) OnConflictColumns(columns ...string) *ProtectedSettingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProtectedSettingUpsertBulk{
		create: _c,
	}
}

// ProtectedSettingUpsertBulk is the builder for "upsert"-ing
// a bulk of ProtectedSetting nodes.
type ProtectedSettingUpsertBulk struct {
	create *ProtectedSettingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ProtectedSetting.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProtectedSettingUpsertBulk) UpdateNewValues() *ProtectedSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProtectedSetting.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProtectedSettingUpsertBulk) Ignore() *ProtectedSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProtectedSettingUpsertBulk) DoNothing() *ProtectedSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProtectedSettingCreateBulk.OnConflict
// documentation for more info.
func (u *ProtectedSettingUpsertBulk) Update(set func(*ProtectedSettingUpsert)) *ProtectedSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProtectedSettingUpsert{UpdateSet: update})
	}))
	return u
}

// SetKey sets the "key" field.
func (u *ProtectedSettingUpsertBulk) SetKey(v string) *ProtectedSettingUpsertBulk {
	return u.Update(func(s *ProtectedSettingUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *ProtectedSettingUpsertBulk) UpdateKey() *ProtectedSettingUpsertBulk {
	return u.Update(func(s *ProtectedSettingUpsert) {
		s.UpdateKey()
	})
}

// SetEnvelope sets the "envelope" field.
func (u *ProtectedSettingUpsertBulk) SetEnvelope(v string) *ProtectedSettingUpsertBulk {
	return u.Update(func(s *ProtectedSettingUpsert) {
		s.SetEnvelope(v)
	})
}

// UpdateEnvelope sets the "envelope" field to the value that was provided on create.
func (u *ProtectedSettingUpsertBulk) UpdateEnvelope() *ProtectedSettingUpsertBulk {
	return u.Update(func(s *ProtectedSettingUpsert) {
		s.UpdateEnvelope()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProtectedSettingUpsertBulk) SetUpdatedAt(v time.Time) *ProtectedSettingUpsertBulk {
	return u.Update(func(s *ProtectedSettingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProtectedSettingUpsertBulk) UpdateUpdatedAt() *ProtectedSettingUpsertBulk {
	return u.Update(func(s *ProtectedSettingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ProtectedSettingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ProtectedSettingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProtectedSettingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProtectedSettingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
